### ISSUE TITLE
Is there a way to train in a way that consumes less VRAM?

### ISSUE THREAD

**Issue by yutaokuyama** [huangyangyi/ELICIT#5]
Hi, thanks for your excellent research.
I would like to do a new training to compare your method with the method I am researching.
Due to limited computing resources, I would like to keep the VRAM consumption to about 48 GB, is it possible to do so through a configuration item?

Thank you in advance.

**Comment by huangyangyi** [comment]
You can try using smaller `N_samples` and `patch.size` in the config file for less VRAM consumption, for instance `N_samples: 64` `size: 256`. Note the performance is not guaranteed for this configuration.

**Comment by yutaokuyama** [comment]
Thank you for your response. I really appreciate it.
