### ISSUE TITLE
where is this file? "dataset/zju_mocap/394\\canonical_joints.pkl"

### ISSUE THREAD

**Issue by ripperthejack** [huangyangyi/ELICIT#7]
where is this file? "dataset/zju_mocap/394\\canonical_joints.pkl"

**Comment by ripperthejack** [comment]
i can not find it in any google drive you provided

**Comment by Coder-ZZY** [comment]
me too.....

**Comment by huangyangyi** [comment]
Hi @ripperthejack @Coder-ZZY , sorry for the late reply, you need to download the ZJU-Mocap dataset and run the preprocessing steps in https://github.com/huangyangyi/ELICIT/blob/main/docs/data.md to get the `canonical_joints.pkl` file.
